# Canonicalise to www
[[redirects]]
from = "https://homeorg.com.au/*"
to = "https://www.homeorg.com.au/:splat"
status = 301
force = true

# HSTS — cautious, covers the apex; don't use includeSubDomains yet
[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=15552000"