backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"      # where files go in repo
public_folder: "/uploads"           # how the site references them

site_url: "https://homeorg.com.au"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Path", name: "path", widget: "string", hint: "/about, /services" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Hero Image", name: "hero", widget: "image", required: false }
